/*
 * mini-cp is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License  v3
 * as published by the Free Software Foundation.
 *
 * mini-cp is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY.
 * See the GNU Lesser General Public License  for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with mini-cp. If not, see http://www.gnu.org/licenses/lgpl-3.0.en.html
 *
 * Copyright (c)  2018. by Laurent Michel, Pierre Schaus, Pascal Van Hentenryck
 */

package minicp.ANDOR_engine;

import minicp.engine.core.IntVar;
import minicp.engine.core.Solver;
import minicp.search.DFSListener;
import minicp.search.SearchStatistics;
import minicp.search.StopSearchException;
import minicp.state.StateManager;
import minicp.util.Procedure;
import minicp.util.exception.InconsistencyException;
import minicp.util.exception.NotImplementedException;

import java.util.*;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Function;
import java.util.function.Supplier;

/**
 * Depth First Search Branch and Bound implementation
 */
public class AND_DFSearch_partial_solution {

    private Solver cp;
    private StateManager sm;
    private Supplier<Branch> treeBuilding;
    private Function<Set<IntVar>, Procedure[]> branching;

    private List<DFSListener> dfsListeners = new LinkedList<DFSListener>();

    private int currNodeIdId;

    private int solutionLimit = Integer.MAX_VALUE;
    private boolean complete = true;

    /**
     * Creates a Depth First Search object with a given branching
     * that defines the search tree dynamically.
     *
     */

    public AND_DFSearch_partial_solution(Solver cp, Supplier<Branch> treeBuilding, Function<Set<IntVar>, Procedure[]> branching) {
        this.cp = cp;
        this.sm = cp.getStateManager();
        this.treeBuilding = treeBuilding;
        this.branching = branching;
    }

    public void setBranching(Function<Set<IntVar>, Procedure[]> branching) {
        this.branching = branching;
    }

    public void setTreeBuilding(Supplier<Branch> treeBuilding) {
        this.treeBuilding = treeBuilding;
    }

    /**
     * Adds a listener that is called on each solution.
     *
     * @param listener the closure to be called whenever a solution is found
     */
    public void onSolution(Procedure listener) {
        dfsListeners.add(new DFSListener() {
            @Override
            public void solution(int pId, int id, int position) {
                listener.call();
            }
        });
    }

    public void addListener(DFSListener listener) {
        dfsListeners.add(listener);
    }

    /**
     * Adds a listener that is called whenever a failure occurs
     * and the search backtracks.
     * This happensthat when a {@link InconsistencyException} is thrown
     * when executing the closure generated by the branching.
     *
     * @param listener the closure to be called whenever a failure occurs and
     *                 the search need to backtrack
     */
    public void onFailure(Procedure listener) {
        dfsListeners.add(new DFSListener() {
            @Override
            public void fail(int pId, int id, int position) {
                listener.call();
            }
        });
    }

    private void notifySolution(int parentId, int nodeId, int position) {
        dfsListeners.forEach(l -> l.solution(parentId, nodeId, position));
    }

    private void notifyFailure(int parentId, int nodeId, int position) {
        dfsListeners.forEach(l -> l.fail(parentId, nodeId, position));
    }

    private void notifyBranch(int parentId, int nodeId, int position, int nChilds) {
        dfsListeners.forEach(l -> l.branch(parentId, nodeId, position, nChilds));
    }

    private SearchStatistics solve( SearchStatistics statistics, int solutionLimit) {
        currNodeIdId = 0;
        this.solutionLimit = solutionLimit;
        sm.withNewState(() -> {
            try {
                int nSolutions = dfs(statistics, -1, -1, 0);
                statistics.incrSolutions(nSolutions);
                if (this.complete) statistics.setCompleted();
            } catch (StopSearchException ignored) {
            } catch (StackOverflowError e) {
                throw new NotImplementedException("dfs with explicit stack needed to pass this test");
            }
        });
        return statistics;
    }

    public SearchStatistics solve(int solutionLimit) {
        SearchStatistics statistics = new SearchStatistics();
        return solve(statistics, solutionLimit);
    }

    public SearchStatistics solve() {
        SearchStatistics statistics = new SearchStatistics();
        return solve(statistics, Integer.MAX_VALUE);
    }


    private int dfs(SearchStatistics statistics, int parentId, int position, int andLevel) {
        Objects.requireNonNull(this.branching, "No branching instruction");
        Objects.requireNonNull(this.treeBuilding, "No tree building instruction");

        Branch branch = treeBuilding.get();
        if (branch == null) {
            System.out.println("treeBuilding doesn't give any proposition");
            return -1;
        }

        int n_Solutions = 0;
        if (branch.getVariables() != null && !branch.getVariables().isEmpty()) {
            n_Solutions = processOrBranch(branch, statistics, parentId, position, andLevel);
        } else if (branch.getBranches() != null && branch.getBranches().length > 0){
            n_Solutions = processAndBranch(branch, statistics, parentId, position, andLevel);
        } else {
            throw new IllegalArgumentException("No branch available");
        }
        return n_Solutions;
    }

    private int processAndBranch(Branch branch, SearchStatistics statistics, int parentId, int position, int AndLevel){
        final int nodeId = currNodeIdId++;
        System.out.println("AND branch of depth "+AndLevel+" =================================================");
        notifySolution(parentId,nodeId, position);
        int pos = 0;
        final int[] nSolutions = {1};
        int a = 0;
        AtomicReference<Boolean> breaking = new AtomicReference<>(false);
        for (SubBranch B : branch.getBranches()) {
            System.out.println("Depth "+ AndLevel +", sub-branch n° " + (a+1) + " \t----------------------");
            a++;
            final int p = pos;
            sm.withNewState(() -> {
                this.cp.getGraphWithStart().newState(B.getVariables());
                int solution = 1;
                if (B.getToFix()) {
                    solution = processOrBranch(new Branch(B.getVariables()), statistics, parentId, position, AndLevel+1);
                } else {
                    solution = dfs(statistics, nodeId, p, AndLevel+1);
                }
                if (solution == 0) breaking.set(true);
                nSolutions[0] *= solution;
            });
            if (breaking.get()) {
                return 0;
            }
            pos += 1;
        }
        return nSolutions[0];
    }

    private int processOrBranch(Branch branch, SearchStatistics statistics, int parentId, int position, int AndLevel){
        final int nodeId = currNodeIdId++;
        Procedure[] branches = new Procedure[0];
        if (branch.getVariables() != null){
            branches = this.branching.apply(branch.getVariables());
            notifyBranch(parentId,nodeId, position, branch.getVariables().size());
        }
        int pos = 0;
        if (branches.length == 0) {
            System.out.println();
            if (cp.getGraphWithStart().solutionFound()){
                notifySolution(parentId,nodeId, position);
                return 1;
            } else if (branch.getBranches() == null ){
                return dfs(statistics, nodeId, pos, AndLevel);
            } else {
                final int p = pos;
                return processAndBranch(new Branch(branch.getBranches()), statistics, nodeId, p, AndLevel);

            }
        } else {
            final int[] nSolutions = {0};
            for (Procedure b : branches) {
                if (nSolutions[0] >= this.solutionLimit) {
                    this.complete = false;
                    break;
                }
                final int p = pos;
                sm.withNewState(() -> {
                    try {
                        statistics.incrNodes();
                        b.call();
                        nSolutions[0] += processOrBranch(branch,statistics, nodeId, p, AndLevel);

                    } catch (InconsistencyException e) {
                        currNodeIdId++;
                        statistics.incrFailures();
                        notifyFailure(parentId,nodeId, p);
                    }
                });
                pos += 1;
            }
            return nSolutions[0];
        }
    }
}