/*
 * mini-cp is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License  v3
 * as published by the Free Software Foundation.
 *
 * mini-cp is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY.
 * See the GNU Lesser General Public License  for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with mini-cp. If not, see http://www.gnu.org/licenses/lgpl-3.0.en.html
 *
 * Copyright (c)  2018. by Laurent Michel, Pierre Schaus, Pascal Van Hentenryck
 */

package minicp.ANDOR_engine;

import minicp.engine.core.IntVar;
import minicp.engine.core.Solver;
import minicp.search.DFSListener;
import minicp.search.SearchStatistics;
import minicp.search.StopSearchException;
import minicp.state.StateManager;
import minicp.util.Procedure;
import minicp.util.exception.InconsistencyException;
import minicp.util.exception.NotImplementedException;

import java.util.*;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Function;
import java.util.function.Supplier;

import static minicp.ANDOR_engine.SlicedTable.computeSlicedTable;

/**
 * Depth First Search Branch and Bound implementation
 */
public class AND_DFSearch {

    private Solver cp;
    private Supplier<Branch> treeBuilding = null;
    private StateManager sm;
    private Function<IntVar[], Procedure[]> branching;

    private List<DFSListener> dfsListeners = new LinkedList<DFSListener>();

    private int currNodeIdId;

    private int solutionLimit = Integer.MAX_VALUE;
    private boolean complete = true;

    /**
     * Creates a Depth First Search object with a given branching
     * that defines the search tree dynamically.
     *
     */

    public AND_DFSearch(Solver cp, Supplier<Branch> treeBuilding, Function<IntVar[], Procedure[]> branching) {
        this.cp = cp;
        this.sm = cp.getStateManager();
        this.treeBuilding = treeBuilding;
        this.branching = branching;
    }

    public void setBranching(Function<IntVar[], Procedure[]> branching) {
        this.branching = branching;
    }

    public void setTreeBuilding(Supplier<Branch> treeBuilding) {
        this.treeBuilding = treeBuilding;
    }

    /**
     * Adds a listener that is called on each solution.
     *
     * @param listener the closure to be called whenever a solution is found
     */
    public void onSolution(Procedure listener) {
        dfsListeners.add(new DFSListener() {
            @Override
            public void solution(int pId, int id, int position) {
                listener.call();
            }
        });
    }


    public void addListener(DFSListener listener) {
        dfsListeners.add(listener);
    }

    /**
     * Adds a listener that is called whenever a failure occurs
     * and the search backtracks.
     * This happensthat when a {@link InconsistencyException} is thrown
     * when executing the closure generated by the branching.
     *
     * @param listener the closure to be called whenever a failure occurs and
     *                 the search need to backtrack
     */
    public void onFailure(Procedure listener) {
        dfsListeners.add(new DFSListener() {
            @Override
            public void fail(int pId, int id, int position) {
                listener.call();
            }
        });
    }


    private void notifySolution() {
        dfsListeners.forEach(l -> l.solution(0, 0, 0));
    }

    private void notifyFailure(int parentId, int nodeId, int position) {
        dfsListeners.forEach(l -> l.fail(parentId, nodeId, position));
    }

    private void notifyBranch(int parentId, int nodeId, int position, int nChilds) {
        dfsListeners.forEach(l -> l.branch(parentId, nodeId, position, nChilds));
    }

    private SearchStatistics solve( SearchStatistics statistics, int solutionLimit, boolean showSolutions) {
        currNodeIdId = 0;
        this.solutionLimit = solutionLimit;
        sm.withNewState(() -> {
            try {
                long debut = System.nanoTime();
                List<SlicedTable> solutions = dfs(statistics, -1, -1);
                long fin = System.nanoTime();
                System.out.format("\nDFS execution time : %s ms\n", (fin - debut) / 1_000_000);

                if (solutions.isEmpty()) {
                    throw new RuntimeException("No solution found");
                }

                List<Map<Integer, Integer>> listSolutions = computeSlicedTable(solutions,solutionLimit);

                statistics.incrSolutions(listSolutions.size());
                if (showSolutions){
                    Set<IntVar> vars = this.cp.getGraphWithStart().getStateVariables();
                    int n_solutions = 0;
                    for (Map<Integer, Integer> sol : listSolutions) {
                        sm.withNewState(() -> {
                            for (IntVar var : vars) {
                                if (sol.containsKey(var.getId())) {
                                    int value = sol.get(var.getId());
                                    var.fix(value);
                                } else {
                                    throw new RuntimeException("no solution for " + var.getId());
                                }
                            }
                            notifySolution();
                        });
                        n_solutions++;
                        if (n_solutions >= solutionLimit) {
                            break;
                        }
                    }
                }

                if (this.complete) statistics.setCompleted();
            } catch (StopSearchException ignored) {
            } catch (StackOverflowError e) {
                throw new NotImplementedException("dfs with explicit stack needed to pass this test");
            }
        });
        return statistics;
    }

    public SearchStatistics solve(int solutionLimit, boolean showSolutions) {
        SearchStatistics statistics = new SearchStatistics();
        return solve(statistics, solutionLimit, showSolutions);
    }

    public SearchStatistics solve(int solutionLimit) {
        SearchStatistics statistics = new SearchStatistics();
        return solve(statistics, solutionLimit, true);
    }

    public SearchStatistics solve(boolean showSolutions) {
        SearchStatistics statistics = new SearchStatistics();
        return solve(statistics, Integer.MAX_VALUE, showSolutions);
    }

    public SearchStatistics solve() {
        SearchStatistics statistics = new SearchStatistics();
        return solve(statistics, Integer.MAX_VALUE, true);
    }

    public Map<Integer, Integer> getPattern() {
        Map<Integer, Integer> pattern = new HashMap<>();
        for (IntVar vars : this.cp.getGraphWithStart().getStateVariables()){
            if (vars.isFixed()) {
                pattern.put(vars.getId(),vars.min());
            }
        }
        if (pattern.isEmpty()) return null;
        return pattern;
    }


    private List<SlicedTable> dfs(SearchStatistics statistics, int parentId, int position) {
        Objects.requireNonNull(this.branching, "No branching instruction");
        Objects.requireNonNull(this.treeBuilding, "No tree building instruction");

        Branch branch = treeBuilding.get();
        if (branch == null) {
            System.out.println("treeBuilding doesn't give any proposition");
            return null;
        }

        List<SlicedTable> solutions;
        if (branch.getVariables() == null & branch.getBranches() != null){
            solutions = new ArrayList<>();
            SlicedTable end = processAndBranch(branch, statistics, parentId, position);
            if (end != null) solutions.add(end);
        } else if (branch.getVariables() != null) {
            solutions = processOrBranch(branch, statistics, parentId, position);
        } else {
            throw new IllegalArgumentException("No branch available");
        }
        return solutions;
    }

    private SlicedTable processAndBranch(Branch branch, SearchStatistics statistics, int parentId, int position){
        final int nodeId = currNodeIdId++;
        int pos = 0;
        List<List<SlicedTable>> subSolutions = new ArrayList<>();
        AtomicReference<Boolean> breaking = new AtomicReference<>(false);
        for (SubBranch B : branch.getBranches()) {
            final int p = pos;
            sm.withNewState(() -> {
                this.cp.getGraphWithStart().newState(B.getVariables());
                List<SlicedTable> get ;
                if (B.getToFix()) {
                    get = processOrBranch(new Branch(B.getVariables()), statistics, parentId, position);
                    if (this.complete) statistics.setCompleted();
                } else {
                    get = dfs(statistics, nodeId, p);
                }
                if (!get.isEmpty()) {
                    subSolutions.add(get);
                } else {
                    breaking.set(true);
                }
            });
            if (breaking.get()) {
                return null;
            }
            pos += 1;
        }
        return new SlicedTable(getPattern(), subSolutions);
    }

    private List<SlicedTable> processOrBranch(Branch branch, SearchStatistics statistics, int parentId, int position){
        final int nodeId = currNodeIdId++;
        Procedure[] branches = new Procedure[0];
        if (branch.getVariables() != null){
            branches = this.branching.apply(branch.getVariables());
            notifyBranch(parentId,nodeId, position, branch.getVariables().length);
        }
        int pos = 0;
        List<SlicedTable> solutions = new ArrayList<>();
        if (branches.length == 0) {
            // SOLUTION
            if (cp.getGraphWithStart().solutionFound()){
                solutions.add(new SlicedTable(getPattern()));
                return solutions;
            } else if (branch.getBranches() == null ){
                List<SlicedTable> end = dfs(statistics, nodeId, pos);
                if (end.isEmpty()) {
                    return solutions;
                }
                return end;
            } else {
                final int p = pos;
                SlicedTable end = processAndBranch(new Branch(branch.getBranches()), statistics, nodeId, p);
                if (end != null) solutions.add(end);
                return solutions;
            }
        } else {
            for (Procedure b : branches) {
                if (solutions.size() >= solutionLimit) {
                    this.complete = false;
                    break;
                }
                final int p = pos;
                sm.withNewState(() -> {
                    try {
                        statistics.incrNodes();
                        b.call();
                        List<SlicedTable> get = processOrBranch(branch,statistics, nodeId, p);
                        solutions.addAll(get);
                    } catch (InconsistencyException e) {
                        currNodeIdId++;
                        statistics.incrFailures();
                        notifyFailure(parentId,nodeId, p);
                    }
                });
                pos += 1;
            }
            return solutions;
        }
    }
}